/**
 * Launch Firefox with the extension loaded, on royalroad.com, already opted in
 * to the redesign.
 *
 *   npm start                  persistent profile in .dev-profile/
 *   npm start -- --legacy      open on the OLD layout instead, to test the
 *                              "switch to the new design" notice and setting
 *   npm start -- --fresh       throwaway profile, what plain `web-ext run` gives
 *   npm start -- --devtools    anything else is handed straight to web-ext
 *
 * Why this exists: Royal Road serves the redesign only when the `beta-ui-v2`
 * cookie is set, and this extension is deliberately inert on the legacy layout.
 * So every session used to begin by pasting a document.cookie line into the
 * console and reloading. That recipe stays in README.md and CONTRIBUTING.md
 * because bug reporters need it too, but nobody should have to type it to work
 * on the extension. Only page-side JavaScript can set the cookie - the server
 * never sends it - so the automation has to be a content script.
 *
 * Why a generated tree under dist/ rather than a dev script in src/:
 * tools/build.mjs copies an allowlist precisely so that tooling cannot reach a
 * store upload, and its header pins the checked-in manifest.json as *the*
 * Firefox manifest. A dev content script living in src/ would break both, and
 * would also silently cookie anyone following README's "Load Temporary Add-on
 * -> pick manifest.json" route. So the tree is assembled here instead: the real
 * src/ and icons/, plus a manifest carrying one extra document_start script.
 * dist/ is already gitignored, and the ship path never learns any of this.
 *
 * The price of that choice is live reload, since web-ext watches its
 * --source-dir and that is now a copy. Hence the watcher below, which re-syncs
 * the copy and lets web-ext notice. It writes over the tree in place and never
 * removes it first, so web-ext can never catch it without a manifest.
 */

import { spawn } from 'node:child_process';
import { existsSync, watch } from 'node:fs';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEV = path.join(ROOT, 'dist', 'dev');
const PROFILE = path.join(ROOT, '.dev-profile');
const WEB_EXT = path.join(ROOT, 'node_modules', 'web-ext', 'bin', 'web-ext.js');

const START_URL = 'https://www.royalroad.com/';

/**
 * What the dev tree needs in order to run. Deliberately not build.mjs's
 * PAYLOAD: LICENSE ships because both stores show reviewers the package
 * contents, and none of that applies to a temporary add-on that never leaves
 * this machine.
 */
const PAYLOAD = ['src', 'icons'];

/** Where the cookie script lands inside the dev tree, as the manifest sees it. */
const COOKIE_JS = 'dev/beta-cookie.js';

/**
 * The whole of the dev-only content script. Kept as a string rather than a file
 * under tools/ so there is no way to mistake it for something that ships: it
 * exists only inside dist/dev, and is rewritten on every launch.
 */
const COOKIE_SRC = `'use strict';

/**
 * Generated by tools/dev.mjs - not part of the extension.
 *
 * Royal Road serves its redesign only when this cookie is set, and the server
 * never sets it for you. A content script shares the page's cookie jar, so this
 * is exactly the line README.md tells you to paste into the console.
 */
(function () {
  var VALUE = 'beta-ui-v2=always';
  var PRESENT = /(?:^|;\\s*)beta-ui-v2=always(?:\\s*;|$)/;
  var FLAG = 'rrx-dev-beta-reloaded';

  // Already opted in. Do nothing at all, so an ordinary reload is undisturbed.
  if (PRESENT.test(document.cookie)) return;

  document.cookie = VALUE + '; path=/; domain=.royalroad.com';

  // Only reload if the cookie actually stuck. Reloading after a rejected write
  // would land right back here with nothing changed, forever.
  if (!PRESENT.test(document.cookie)) {
    console.warn('[rr-ui dev] could not set ' + VALUE + ' - still on the legacy UI');
    return;
  }

  // Second guard, independent of the first: at most one reload per tab per
  // session whatever else goes wrong. sessionStorage throws when storage is
  // restricted, and a dev convenience must never be the thing that breaks the
  // page, so failing to read it means failing to reload.
  try {
    if (sessionStorage.getItem(FLAG)) return;
    sessionStorage.setItem(FLAG, '1');
  } catch (err) {
    return;
  }

  location.reload();
})();
`;

/**
 * The opposite: put the profile back on the legacy layout, once.
 *
 * Needed because the extension now does something there - it offers to switch,
 * and can be set to switch by itself - and that is impossible to test from a
 * profile permanently opted in to the redesign, which is exactly what the
 * persistent .dev-profile becomes after one ordinary `npm start`.
 *
 * The cookie is deleted rather than set to some made-up value, because the case
 * worth testing is a reader who never opted in, and that is what their profile
 * looks like.
 *
 * "Once" is the whole difficulty. Clearing on every load would fight the
 * extension's own automatic switch: it sets the cookie and reloads, this clears
 * it and reloads, forever, and the tab is unusable. Clearing once per tab
 * instead means the first load is legacy - which is what was asked for - and
 * whatever the extension does next is left alone and can be watched.
 */
const LEGACY_SRC = `'use strict';

/**
 * Generated by tools/dev.mjs - not part of the extension.
 *
 * Puts this tab on Royal Road's legacy layout by removing the opt-in cookie,
 * once, so the extension's "switch to the new design" behaviour can be tested.
 */
(function () {
  var PRESENT = /(?:^|;\\s*)beta-ui-v2=/;
  var FLAG = 'rrx-dev-legacy-cleared';

  // No opt-in to remove: this profile is already seeing the legacy layout.
  if (!PRESENT.test(document.cookie)) return;

  // Already cleared once in this tab. Anything setting the cookie after that is
  // the extension under test, and must be left to do it.
  try {
    if (sessionStorage.getItem(FLAG)) return;
    sessionStorage.setItem(FLAG, '1');
  } catch (err) {
    // Without the guard this would loop, so refuse rather than risk it.
    console.warn('[rr-ui dev] no sessionStorage, so --legacy will not clear the cookie');
    return;
  }

  document.cookie = 'beta-ui-v2=; path=/; domain=.royalroad.com; max-age=0';

  if (PRESENT.test(document.cookie)) {
    console.warn('[rr-ui dev] could not clear beta-ui-v2 - still on the redesign');
    return;
  }

  location.reload();
})();
`;

/**
 * Prepend the cookie script to the existing document_start block rather than
 * giving it a block of its own: one fewer difference between the dev manifest
 * and the real one, and it puts the cookie in place before boot.js runs.
 *
 * @param {object} manifest the checked-in Firefox manifest, already parsed
 */
function toDev(manifest) {
  const next = structuredClone(manifest);
  const start = (next.content_scripts ?? []).find((block) => block.run_at === 'document_start');
  if (!start) {
    throw new Error(
      `manifest.json has no document_start content script, so ${COOKIE_JS} has nowhere to go. ` +
        'Firefox would open on the legacy UI with nothing to say why.'
    );
  }
  start.js = [COOKIE_JS, ...(start.js ?? [])];
  return next;
}

/**
 * Assemble dist/dev. `clean` wipes first, which only the initial build does:
 * the watcher re-syncs in place so web-ext never observes the tree mid-rebuild,
 * and above all never without a manifest, which would end the run.
 *
 * The manifest is written last for the same reason - it is the file web-ext
 * cares most about, so it should settle after everything it points at.
 */
async function emit({ clean = false, legacy = false } = {}) {
  if (clean) await rm(DEV, { recursive: true, force: true });
  await mkdir(path.join(DEV, path.dirname(COOKIE_JS)), { recursive: true });
  for (const entry of PAYLOAD) {
    await cp(path.join(ROOT, entry), path.join(DEV, entry), { recursive: true, force: true });
  }
  await writeFile(path.join(DEV, COOKIE_JS), legacy ? LEGACY_SRC : COOKIE_SRC, 'utf8');
  const manifest = JSON.parse(await readFile(path.join(ROOT, 'manifest.json'), 'utf8'));
  await writeFile(
    path.join(DEV, 'manifest.json'),
    `${JSON.stringify(toDev(manifest), null, 2)}\n`,
    'utf8'
  );
}

/**
 * Mirror source edits into the dev tree so web-ext's reloader still fires.
 *
 * Debounced at 100ms because one editor save can produce several events;
 * web-ext then debounces its own watcher by 500ms on top, so a burst of saves
 * still costs exactly one extension reload.
 *
 * @returns {() => void} stops watching
 */
function watchSources(legacy) {
  let timer = null;
  let running = false;
  let queued = false;

  function bump() {
    clearTimeout(timer);
    timer = setTimeout(sync, 100);
  }

  async function sync() {
    timer = null;
    if (running) {
      queued = true;
      return;
    }
    running = true;
    try {
      await emit({ legacy });
    } catch (err) {
      console.error(`  re-sync failed: ${err.message}`);
    }
    running = false;
    if (queued) {
      queued = false;
      bump();
    }
  }

  const watchers = [
    watch(path.join(ROOT, 'src'), { recursive: true }, bump),
    watch(path.join(ROOT, 'icons'), { recursive: true }, bump),
    watch(path.join(ROOT, 'manifest.json'), bump),
  ];
  return () => {
    clearTimeout(timer);
    for (const watcher of watchers) watcher.close();
  };
}

// --- run ---------------------------------------------------------------------

const argv = process.argv.slice(2);
const fresh = argv.includes('--fresh');
const legacy = argv.includes('--legacy');
const passthrough = argv.filter((arg) => arg !== '--fresh' && arg !== '--legacy');

if (!existsSync(WEB_EXT)) {
  throw new Error(`${WEB_EXT} is missing. Run \`npm install\` first.`);
}

const manifest = JSON.parse(await readFile(path.join(ROOT, 'manifest.json'), 'utf8'));
console.log(`Launching ${manifest.name} ${manifest.version}`);

await emit({ clean: true, legacy });
console.log('  dist/dev');
console.log(
  legacy
    ? '  legacy layout (the extension should offer to switch you)'
    : '  redesign'
);

// web-ext's own --profile-create-if-missing uses a non-recursive mkdir, and it
// wants an absolute path or it will read the value as a profiles.ini name.
// Doing it here first means neither can surprise us.
//
// Whether the profile already existed is worth saying out loud. The whole point
// of keeping it is not logging in to Royal Road again every launch, and a
// profile that has quietly gone missing looks identical at startup to one that
// is being reused: you only find out when the site asks you to log in. It is
// gitignored, so `git clean -fdx` takes it, as does anything that tidies
// untracked files.
const reusing = !fresh && existsSync(PROFILE);
if (!fresh) await mkdir(PROFILE, { recursive: true });
console.log(
  fresh
    ? '  throwaway profile'
    : reusing
      ? '  profile .dev-profile (reusing: you should still be logged in)'
      : '  profile .dev-profile (new: you will have to log in once)'
);
console.log(`  ${START_URL}`);

const stopWatching = watchSources(legacy);

const child = spawn(
  process.execPath,
  [
    WEB_EXT,
    'run',
    // A CLI --source-dir beats package.json's webExt.sourceDir, so the config
    // block there still serves a bare `npx web-ext run` on the repo root.
    '--source-dir',
    DEV,
    '--start-url',
    START_URL,
    // --fresh has to drop --firefox-profile as well, not just the two flags
    // after it: a profile *without* --keep-profile-changes makes web-ext run
    // from a throwaway copy of .dev-profile, which is a third mode nobody
    // asked for.
    ...(fresh
      ? []
      : ['--firefox-profile', PROFILE, '--keep-profile-changes', '--profile-create-if-missing']),
    ...passthrough,
  ],
  { cwd: ROOT, stdio: 'inherit' }
);

// A console delivers Ctrl-C to every attached process, so this one gets it too.
// Leaving it to the default handler would hand the prompt back while Firefox is
// still up, so the first one is web-ext's business: on a TTY it reads Ctrl-C as
// a keypress and shuts the browser down in order, and without one it takes the
// signal itself. Either way the child's exit is what ends us. A second Ctrl-C
// means neither happened, so stop waiting.
let interrupts = 0;
process.on('SIGINT', () => {
  if ((interrupts += 1) > 1) {
    stopWatching();
    process.exit(130);
  }
});

child.on('exit', (code, signal) => {
  stopWatching();
  process.exit(code ?? (signal ? 1 : 0));
});
