/**
 * Launch Firefox with the extension loaded, on royalroad.com, already opted in
 * to the redesign.
 *
 *   npm start                  persistent profile in .dev-profile/
 *   npm start -- --legacy      open on the OLD layout instead, to test the
 *                              design switch in the popup
 *   npm start -- --fresh       throwaway profile, what plain `web-ext run` gives
 *   npm start -- --devtools    anything else goes to web-ext, as --flag or
 *                              --flag=value
 *
 * Why this exists: Royal Road serves the redesign only when the `rr_ui_mode`
 * cookie asks for it, and this extension is deliberately inert on the legacy
 * layout. So every session used to begin by pasting a document.cookie line into
 * the console and reloading. That recipe stays in README.md and CONTRIBUTING.md
 * because bug reporters need it too, but nobody should have to type it to work
 * on the extension. Only page-side JavaScript asks for the redesign - the server
 * never sends `rr_ui_mode=redesign` - so the automation has to be a content script.
 *
 * Why a generated tree under dist/ rather than a dev script in src/:
 * tools/build.mjs copies an allowlist precisely so that tooling cannot reach a
 * store upload, and its header pins the checked-in manifest.json as *the*
 * Firefox manifest. A dev content script living in src/ would break both, and
 * would also silently cookie anyone following README's "Load Temporary Add-on
 * -> pick manifest.json" route. So the tree is assembled here instead: the real
 * src/ and icons/, plus a manifest carrying one extra document_start script.
 * dist/ is already gitignored, and the ship path never learns any of this.
 *
 * The price of that choice is live reload, since web-ext watches its
 * --source-dir and that is now a copy. Hence the watcher below, which re-syncs
 * the copy and lets web-ext notice. It writes over the tree in place and never
 * removes it first, so web-ext can never catch it without a manifest.
 */

import { existsSync, watch } from 'node:fs';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import webExt from 'web-ext';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEV = path.join(ROOT, 'dist', 'dev');
const PROFILE = path.join(ROOT, '.dev-profile');

const START_URL = 'https://www.royalroad.com/';

/**
 * What the dev tree needs in order to run. Deliberately not build.mjs's
 * PAYLOAD: LICENSE ships because both stores show reviewers the package
 * contents, and none of that applies to a temporary add-on that never leaves
 * this machine.
 */
const PAYLOAD = ['src', 'icons'];

/** Where the cookie script lands inside the dev tree, as the manifest sees it. */
const COOKIE_JS = 'dev/layout-cookie.js';

/** New on every launch, so the redesign script acts once per `npm start`. */
const LAUNCH = String(Date.now());

/**
 * The whole of the dev-only content script. Kept as a string rather than a file
 * under tools/ so there is no way to mistake it for something that ships: it
 * exists only inside dist/dev, and is rewritten on every launch.
 */
const COOKIE_SRC = `'use strict';

/**
 * Generated by tools/dev.mjs - not part of the extension.
 *
 * Royal Road serves its redesign only when this cookie asks for it, and the
 * server never sets it for you. A content script shares the page's cookie jar,
 * so this is the cookie README.md tells you to set by hand, for the session only.
 */
(function () {
  var VALUE = 'rr_ui_mode=redesign';
  var PRESENT = /(?:^|;\\s*)rr_ui_mode=redesign(?:\\s*;|$)/;
  var KEY = 'rrx-dev-launch';
  var LAUNCH = '${LAUNCH}';

  // Once per launch, checked before the write: writing on every load undid
  // Royal Road's own switch and the extension's "old design" alike, so every
  // refresh landed on the redesign. localStorage throws when storage is
  // restricted, and a dev convenience must never break the page.
  try {
    if (localStorage.getItem(KEY) === LAUNCH) return;
    localStorage.setItem(KEY, LAUNCH);
  } catch (err) {
    return;
  }

  if (PRESENT.test(document.cookie)) return;

  // Host-only, as Royal Road writes it, so there is one copy and theirs replaces it.
  document.cookie = VALUE + '; path=/; samesite=lax; secure';

  // Only reload if the cookie actually stuck.
  if (!PRESENT.test(document.cookie)) {
    console.warn('[rr-ui dev] could not set ' + VALUE + ' - still on the legacy UI');
    return;
  }

  location.reload();
})();
`;

/**
 * The opposite: put the tab on the legacy layout, once.
 *
 * Needed because the extension can be set to switch layouts by itself, and that
 * cannot be tested from a profile already on the redesign, which is what
 * .dev-profile becomes after one ordinary `npm start`.
 *
 * Written as `legacy` rather than deleted, as Royal Road's own revert does:
 * .dev-profile is signed in, and with no cookie the account's Display Mode may
 * decide instead.
 *
 * "Once" is the whole difficulty. Writing on every load would fight the
 * extension's own switch: it asks for the redesign and reloads, this asks for
 * legacy and reloads, forever. Once per tab means the first load is legacy and
 * whatever the extension does next can be watched.
 */
const LEGACY_SRC = `'use strict';

/**
 * Generated by tools/dev.mjs - not part of the extension.
 *
 * Puts this tab on Royal Road's legacy layout, once, so the extension's design
 * switch can be tested.
 */
(function () {
  var LEGACY = /(?:^|;\\s*)rr_ui_mode=legacy(?:\\s*;|$)/;
  var FLAG = 'rrx-dev-legacy-set';

  if (LEGACY.test(document.cookie)) return;

  // Already done once in this tab. Anything asking for the redesign after that
  // is the extension under test, and must be left to do it.
  try {
    if (sessionStorage.getItem(FLAG)) return;
    sessionStorage.setItem(FLAG, '1');
  } catch (err) {
    // Without the guard this would loop, so refuse rather than risk it.
    console.warn('[rr-ui dev] no sessionStorage, so --legacy will not set the cookie');
    return;
  }

  document.cookie = 'rr_ui_mode=legacy; path=/; samesite=lax; secure';

  if (!LEGACY.test(document.cookie)) {
    console.warn('[rr-ui dev] could not set rr_ui_mode=legacy - still on the redesign');
    return;
  }

  location.reload();
})();
`;

/**
 * Prepend the cookie script to the existing document_start block rather than
 * giving it a block of its own: one fewer difference between the dev manifest
 * and the real one, and it puts the cookie in place before boot.js runs.
 *
 * @param {object} manifest the checked-in Firefox manifest, already parsed
 */
function toDev(manifest) {
  const next = structuredClone(manifest);
  const start = (next.content_scripts ?? []).find((block) => block.run_at === 'document_start');
  if (!start) {
    throw new Error(
      `manifest.json has no document_start content script, so ${COOKIE_JS} has nowhere to go. ` +
        'Firefox would open on the legacy UI with nothing to say why.'
    );
  }
  start.js = [COOKIE_JS, ...(start.js ?? [])];
  return next;
}

/**
 * Assemble dist/dev. `clean` wipes first, which only the initial build does:
 * the watcher re-syncs in place so web-ext never observes the tree mid-rebuild,
 * and above all never without a manifest, which would end the run.
 *
 * The manifest is written last for the same reason - it is the file web-ext
 * cares most about, so it should settle after everything it points at.
 */
async function emit({ clean = false, legacy = false } = {}) {
  if (clean) await rm(DEV, { recursive: true, force: true });
  await mkdir(path.join(DEV, path.dirname(COOKIE_JS)), { recursive: true });
  for (const entry of PAYLOAD) {
    await cp(path.join(ROOT, entry), path.join(DEV, entry), { recursive: true, force: true });
  }
  await writeFile(path.join(DEV, COOKIE_JS), legacy ? LEGACY_SRC : COOKIE_SRC, 'utf8');
  const manifest = JSON.parse(await readFile(path.join(ROOT, 'manifest.json'), 'utf8'));
  await writeFile(
    path.join(DEV, 'manifest.json'),
    `${JSON.stringify(toDev(manifest), null, 2)}\n`,
    'utf8'
  );
}

/**
 * Mirror source edits into the dev tree so web-ext's reloader still fires.
 *
 * Debounced at 100ms because one editor save can produce several events;
 * web-ext then debounces its own watcher by 500ms on top, so a burst of saves
 * still costs exactly one extension reload.
 *
 * @returns {() => void} stops watching
 */
function watchSources(legacy) {
  let timer = null;
  let running = false;
  let queued = false;

  function bump() {
    clearTimeout(timer);
    timer = setTimeout(sync, 100);
  }

  async function sync() {
    timer = null;
    if (running) {
      queued = true;
      return;
    }
    running = true;
    try {
      await emit({ legacy });
    } catch (err) {
      console.error(`  re-sync failed: ${err.message}`);
    }
    running = false;
    if (queued) {
      queued = false;
      bump();
    }
  }

  const watchers = [
    watch(path.join(ROOT, 'src'), { recursive: true }, bump),
    watch(path.join(ROOT, 'icons'), { recursive: true }, bump),
    watch(path.join(ROOT, 'manifest.json'), bump),
  ];
  return () => {
    clearTimeout(timer);
    for (const watcher of watchers) watcher.close();
  };
}

// --- run ---------------------------------------------------------------------

const argv = process.argv.slice(2);
const fresh = argv.includes('--fresh');
const legacy = argv.includes('--legacy');
const passthrough = argv.filter((arg) => arg !== '--fresh' && arg !== '--legacy');

const manifest = JSON.parse(await readFile(path.join(ROOT, 'manifest.json'), 'utf8'));
console.log(`Launching ${manifest.name} ${manifest.version}`);

await emit({ clean: true, legacy });
console.log('  dist/dev');
console.log(legacy ? '  legacy layout, once per tab' : '  redesign');

// web-ext's own --profile-create-if-missing uses a non-recursive mkdir, and it
// wants an absolute path or it will read the value as a profiles.ini name.
// Doing it here first means neither can surprise us.
//
// Whether the profile already existed is worth saying out loud. The whole point
// of keeping it is not logging in to Royal Road again every launch, and a
// profile that has quietly gone missing looks identical at startup to one that
// is being reused: you only find out when the site asks you to log in. It is
// gitignored, so `git clean -fdx` takes it, as does anything that tidies
// untracked files.
const reusing = !fresh && existsSync(PROFILE);
if (!fresh) await mkdir(PROFILE, { recursive: true });
console.log(
  fresh
    ? '  throwaway profile'
    : reusing
      ? '  profile .dev-profile (reusing: you should still be logged in)'
      : '  profile .dev-profile (new: you will have to log in once)'
);
console.log(`  ${START_URL}`);

const stopWatching = watchSources(legacy);

/**
 * Anything left after --fresh and --legacy, as `cmd.run` parameters:
 * `--devtools` becomes `{devtools: true}`, `--firefox=nightly` becomes
 * `{firefox: 'nightly'}`. web-ext's own CLI parser cannot do this job here,
 * because `main()` throws away the value its command returns and that value is
 * the runner this file needs.
 */
function paramsFrom(flags) {
  const out = {};
  for (const flag of flags) {
    const m = /^--([a-z][\w-]*)(?:=(.*))?$/i.exec(flag);
    if (!m) {
      throw new Error(`cannot hand ${flag} to web-ext: write it as --flag or --flag=value`);
    }
    out[m[1].replace(/-(\w)/g, (_, c) => c.toUpperCase())] = m[2] === undefined ? true : m[2];
  }
  return out;
}

const end = (code) => {
  stopWatching();
  process.exit(code);
};

let runner;
try {
  runner = await webExt.cmd.run(
    {
      sourceDir: DEV,
      startUrl: START_URL,
      artifactsDir: path.join(ROOT, 'web-ext-artifacts'),
      // web-ext's reload keys would put the terminal in raw mode for as long as
      // the browser is up. Nothing here needs them: the watcher above re-syncs
      // on save and Ctrl-C is handled below.
      noInput: true,
      // --fresh has to drop the profile as well, not just the two flags after
      // it: a profile *without* keepProfileChanges makes web-ext run from a
      // throwaway copy of .dev-profile, which is a third mode nobody asked for.
      ...(fresh
        ? {}
        : { firefoxProfile: PROFILE, keepProfileChanges: true, profileCreateIfMissing: true }),
      ...paramsFrom(passthrough),
    },
    // Throw rather than exiting the process out from under us, so the watcher
    // is stopped and the reason is printed once.
    { shouldExitProgram: false }
  );
} catch (err) {
  console.error(`  ${err.message}`);
  end(1);
}

/**
 * Closing the browser ends the run.
 *
 * This is the hook the whole in-process launch is for. `cmd.run` returns as soon
 * as Firefox is up and never waits for it, so nothing is watching the browser's
 * lifetime; its own open sockets then hold the event loop after the window is
 * closed. Run as a child process that meant `npm start` sat there with no
 * browser and no prompt back, and the next `npm start` had nowhere to go.
 */
let interrupted = false;
runner.registerCleanup(() => end(interrupted ? 130 : 0));

// A console delivers Ctrl-C to every attached process, and web-ext installs no
// handler of its own: left alone it would kill this process and leave Firefox
// running, orphaned, still holding .dev-profile. `exit()` closes the browser,
// which brings us back through the cleanup above. A second Ctrl-C means that did
// not happen, so stop waiting.
process.on('SIGINT', () => {
  if (interrupted) end(130);
  interrupted = true;
  runner.exit().catch(() => end(130));
});
